Dr  Droyne
V4  Ve Ehklle ksafi (40th Squadron)
V9  Infinity League
Va  Vargr non-aligned
Vc  Gnoerrgh Rukh lloell (Anti-Rukh Coalition)
Vk  Kedzudh Aeng (Commonality of Kedzudh)
Vo  Opposition Alliance
Vp  Thirz Uerra (Thirz Empire)
Vq  Dzen Aeng kho (Society of Equals)
Vr  Rukh Aegz (Worlds of Leader Rukh)
Vs  Seaknouth Dependency
Vt  Thoengling Raghz (Thoengling Empire)
VV  Gaerr Thue (Pact of Gaerr)
VW  Rranglloez Oguenten (Rranglloez Stronghold)
Zh  Zhodani

